### ISSUE TITLE
의견: 시간이 부족해서 못했던 챕터 3-4 진행안

### ISSUE THREAD

**Issue by aka-nick** [LetsReadTechBooks/the-essence-of-object-orientation#1]
정리한 내용 텍스트로 업로드 해놓고
서로 읽어보고 이슈로 남겨보면 어떨까요? Labels만 만들어서 붙이면 될 거 같습니다.
일단 저는 /aka-nick 에 올려두었습니다. (PR로 올릴걸 그랬네요, 그럼 comment 남기면 됐을텐데)

**Comment by JuSeong1130** [comment]
빨간줄을 그은건 스터디시간에 서로 발표하면될거같고 이제 막힌부분에 대해서 이슈에 남기는거 좋을거 같습니다 어떤 부분이 막혔는데 어떻게 이해했고 이렇게 해결했다 정도로요

**Comment by aka-nick** [comment]
이전에 이야기 했듯이, 동의합니다!
그리고 이 이슈는 닫겠습니다 😇
